// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArv6blX3H6xRRt7cxJ0ukwY9CEMRi8caA',
    appId: '1:753033980953:web:0a473d547c7d86f49bce88',
    messagingSenderId: '753033980953',
    projectId: 'quiz-146d3',
    authDomain: 'quiz-146d3.firebaseapp.com',
    storageBucket: 'quiz-146d3.firebasestorage.app',
    measurementId: 'G-2F8K4Q798L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBALiNyF17OhGp65Z8YyUTcd0f3ZMs1UKo',
    appId: '1:753033980953:android:521466e87a989d249bce88',
    messagingSenderId: '753033980953',
    projectId: 'quiz-146d3',
    storageBucket: 'quiz-146d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcA9gZay4zDYFfoqVW0HeTg0gQpjwXNa4',
    appId: '1:753033980953:ios:311cdf486ec966129bce88',
    messagingSenderId: '753033980953',
    projectId: 'quiz-146d3',
    storageBucket: 'quiz-146d3.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcA9gZay4zDYFfoqVW0HeTg0gQpjwXNa4',
    appId: '1:753033980953:ios:311cdf486ec966129bce88',
    messagingSenderId: '753033980953',
    projectId: 'quiz-146d3',
    storageBucket: 'quiz-146d3.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArv6blX3H6xRRt7cxJ0ukwY9CEMRi8caA',
    appId: '1:753033980953:web:04ed615db1c69d9a9bce88',
    messagingSenderId: '753033980953',
    projectId: 'quiz-146d3',
    authDomain: 'quiz-146d3.firebaseapp.com',
    storageBucket: 'quiz-146d3.firebasestorage.app',
    measurementId: 'G-NY0ECWW5GJ',
  );
}
